### ISSUE TITLE
[docs] Add ReadME doc

### ISSUE THREAD

**Issue by simon-cj** [kleveross/klever-model-registry#20]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ddysher** [comment]
any progress?  We can have a Chinese version first.

**Comment by simon-cj** [comment]
> any progress? We can have a Chinese version first.

not start yet, recently do research and design doc for model registry first, and then will write a Chinese version.

**Comment by ddysher** [comment]
you don't need a lengthy design doc for readme

**Comment by gaocegege** [comment]
我们的 README 应该可以简单介绍一下这个项目的目标，有一个粗粒度的设计图（包含 ormb，model registry，harbor 这些，展示他们之间的关系）就好了

设计文档需要有一个专门的文档

**Comment by gaocegege** [comment]
I am closing it. Maybe I will revise the doc soon.
