### ISSUE TITLE
[enhancement] Add Unit Test

### ISSUE THREAD

**Issue by simon-cj** [kleveross/klever-model-registry#21]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
Do we have a plan for the issue? I think it will be better if we add unit tests in early stage.

**Comment by simon-cj** [comment]
> Do we have a plan for the issue? I think it will be better if we add unit tests in early stage.

now， the basic API is done after logs API PR https://github.com/kleveross/klever-model-registry/pull/37， and then will add unit test， maybe it will begin today.
