### ISSUE TITLE
您好，使用web做模型转换的时候报错“run model-initializer error”

### ISSUE THREAD

**Issue by FaceGg** [kleveross/klever-model-registry#240]
web端日志显示“container "executor" in pod "modeljob-90360309-20210309093813-z6hkhg8h-77748" is waiting to start: PodInitializing”
##############################################################################################
kubectl get pod
NAME                                              READY   STATUS       RESTARTS   AGE
modeljob-90360309-20210309093813-z6hkhg8h-77748   0/1     Init:Error   0          48s
##############################################################################################
kubectl describe pod modeljob-90360309-20210309093813-z6hkhg8h-77748
Name:         modeljob-90360309-20210309093813-z6hkhg8h-77748
Namespace:    default
Priority:     0
Node:         master/172.27.118.204
Start Time:   Wed, 10 Mar 2021 10:03:54 +0800
Labels:       controller-uid=42c77804-dab5-41db-b523-b8d58a2ca080
              job-name=modeljob-90360309-20210309093813-z6hkhg8h
Annotations:  <none>
Status:       Failed
IP:           10.244.0.63
IPs:
  IP:           10.244.0.63
Controlled By:  Job/modeljob-90360309-20210309093813-z6hkhg8h
Init Containers:
  model-initializer:
    Container ID:  docker://a0fdcf00630e1f9bfbc31ed9468cd890066d7512dcdc2652658b8b0d00852d82
    Image:         ghcr.io/kleveross/klever-ormb-storage-initializer:v0.0.8
    Image ID:      docker-pullable://ghcr.io/kleveross/klever-ormb-storage-initializer@sha256:7379b72aebf5c6411015a7f9416e5e98125b7eded2ac259ebb4311d9ef5a5f20
    Port:          <none>
    Host Port:     <none>
    Args:
      harbor-harbor-core.harbor-system/release/caffemodel:v1
      /models/input
      --relayout=false
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 10 Mar 2021 10:03:59 +0800
      Finished:     Wed, 10 Mar 2021 10:04:14 +0800
    Ready:          False
    Restart Count:  0
    Environment:
      ORMB_USERNAME:  admin
      ORMB_PASSWORD:  ORMBtest12345
    Mounts:
      /models/input from model (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tjsbd (ro)
Containers:
  executor:
    Container ID:
    Image:          ghcr.io/kleveross/caffemodel_to_netdef:v0.3.0-alpha.1
    Image ID:
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      FRAMEWORK:               Caffe2
      FORMAT:                  NetDef
      SOURCE_FORMAT:           CaffeModel
      SOURCE_MODEL_TAG:        klever-model-registry.kleveross-system:8080/release/caffemodel:v1
      DESTINATION_MODEL_TAG:   klever-model-registry.kleveross-system:8080/release/netdef:v2-caffemodel
      SOURCE_MODEL_PATH:       /models/input
      DESTINATION_MODEL_PATH:  /models/output
      EXTRACTOR:               netdef
      SERVER_ORMB_DOMAIN:      klever-model-registry.kleveross-system:8080
      SERVER_ORMB_USERNAME:    admin
      SERVER_ORMB_PASSWORD:    ORMBtest12345
    Mounts:
      /models/input from model (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tjsbd (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  model:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-tjsbd:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tjsbd
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  62s   default-scheduler  Successfully assigned default/modeljob-90360309-20210309093813-z6hkhg8h-77748 to master
  Normal  Pulling    62s   kubelet            Pulling image "ghcr.io/kleveross/klever-ormb-storage-initializer:v0.0.8"
  Normal  Pulled     59s   kubelet            Successfully pulled image "ghcr.io/kleveross/klever-ormb-storage-initializer:v0.0.8" in 3.515655372s
  Normal  Created    58s   kubelet            Created container model-initializer
  Normal  Started    58s   kubelet            Started container model-initializer

**Comment by FogDong** [comment]
方便看下容器日志吗

**Comment by FaceGg** [comment]
@FogDong 
2021-03-10T06:35:13.435Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default"}
2021-03-10T06:35:13.436Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default"}
2021-03-10T06:35:14.350Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ModelJob","namespace":"default","name":"modeljob-90360309-20210309093813-z6hkhg8h","uid":"68b046f5-ad3c-4910-96c9-613c04a3cbcf","apiVersion":"kleveross.io/v1alpha1","resourceVersion":"956519"}, "reason": "Pending", "message": "ModelJob Pending"}
2021-03-10T06:35:14.367Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default"}
2021-03-10T06:35:14.368Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ModelJob","namespace":"default","name":"modeljob-90360309-20210309093813-z6hkhg8h","uid":"68b046f5-ad3c-4910-96c9-613c04a3cbcf","apiVersion":"kleveross.io/v1alpha1","resourceVersion":"956519"}, "reason": "Pending", "message": "ModelJob Pending"}
2021-03-10T06:35:14.386Z        ERROR   controller      Reconciler error        {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default", "error": "Operation cannot be fulfilled on modeljobs.kleveross.io \"modeljob-90360309-20210309093813-z6hkhg8h\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/github.com/go-logr/zapr/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:246
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
        /home/runner/work/klever-model-registry/klever-model-registry/src/github.com/kleveross/klever-model-registry/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
2021-03-10T06:35:15.387Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ModelJob","namespace":"default","name":"modeljob-90360309-20210309093813-z6hkhg8h","uid":"68b046f5-ad3c-4910-96c9-613c04a3cbcf","apiVersion":"kleveross.io/v1alpha1","resourceVersion":"956527"}, "reason": "StartRunning", "message": "ModelJob running"}
2021-03-10T06:35:15.395Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default"}
2021-03-10T06:35:15.395Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default"}
2021-03-10T06:35:15.395Z        DEBUG   controller-runtime.manager.events       Normal  {"object": {"kind":"ModelJob","namespace":"default","name":"modeljob-90360309-20210309093813-z6hkhg8h","uid":"68b046f5-ad3c-4910-96c9-613c04a3cbcf","apiVersion":"kleveross.io/v1alpha1","resourceVersion":"956537"}, "reason": "StartRunning", "message": "ModelJob running"}
2021-03-10T06:35:33.860Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default"}
2021-03-10T06:35:33.861Z        DEBUG   controller      Successfully Reconciled {"reconcilerGroup": "kleveross.io", "reconcilerKind": "ModelJob", "controller": "modeljob", "name": "modeljob-90360309-20210309093813-z6hkhg8h", "namespace": "default"}

**Comment by simon-cj** [comment]
从日志看，modeljob-90360309-20210309093813-z6hkhg8h-77748 任务的 init container 从 harbor 拉去模型失败了，可以在集群上看下pod 的init container 日志，同时把 pod 的 yaml 发出下

**Comment by FaceGg** [comment]
@simon-cj 是这个吗

kind: Pod
apiVersion: v1
metadata:
  name: modeljob-90360309-20210309093813-z6hkhg8h-hpvxb
  generateName: modeljob-90360309-20210309093813-z6hkhg8h-
  namespace: default
  uid: 7dbe1034-287e-47b0-b5c5-e87ec11e44d9
  resourceVersion: '956584'
  creationTimestamp: '2021-03-10T06:35:14Z'
  labels:
    controller-uid: 570d820d-1673-4c50-af9e-9ae271bf7b85
    job-name: modeljob-90360309-20210309093813-z6hkhg8h
  ownerReferences:
    - apiVersion: batch/v1
      kind: Job
      name: modeljob-90360309-20210309093813-z6hkhg8h
      uid: 570d820d-1673-4c50-af9e-9ae271bf7b85
      controller: true
      blockOwnerDeletion: true
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-03-10T06:35:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:controller-uid': {}
            'f:job-name': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"570d820d-1673-4c50-af9e-9ae271bf7b85"}':
              .: {}
              'f:apiVersion': {}
              'f:blockOwnerDeletion': {}
              'f:controller': {}
              'f:kind': {}
              'f:name': {}
              'f:uid': {}
        'f:spec':
          'f:containers':
            'k:{"name":"executor"}':
              .: {}
              'f:env':
                .: {}
                'k:{"name":"DESTINATION_MODEL_PATH"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"DESTINATION_MODEL_TAG"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"EXTRACTOR"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"FORMAT"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"FRAMEWORK"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"SERVER_ORMB_DOMAIN"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"SERVER_ORMB_PASSWORD"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"SERVER_ORMB_USERNAME"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"SOURCE_FORMAT"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"SOURCE_MODEL_PATH"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"SOURCE_MODEL_TAG"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/models/input"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:workingDir': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:initContainers':
            .: {}
            'k:{"name":"model-initializer"}':
              .: {}
              'f:args': {}
              'f:env':
                .: {}
                'k:{"name":"ORMB_PASSWORD"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
                'k:{"name":"ORMB_USERNAME"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/models/input"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
              'f:workingDir': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"model"}':
              .: {}
              'f:emptyDir': {}
              'f:name': {}
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2021-03-10T06:35:33Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:initContainerStatuses': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.244.0.65"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
spec:
  volumes:
    - name: model
      emptyDir: {}
    - name: default-token-tjsbd
      secret:
        secretName: default-token-tjsbd
        defaultMode: 420
  initContainers:
    - name: model-initializer
      image: 'ghcr.io/kleveross/klever-ormb-storage-initializer:v0.0.8'
      args:
        - 'harbor-harbor-core.harbor-system/release/caffemodel:v1'
        - /models/input
        - '--relayout=false'
      workingDir: /models
      env:
        - name: ORMB_USERNAME
          value: admin
        - name: ORMB_PASSWORD
          value: ORMBtest12345
      resources: {}
      volumeMounts:
        - name: model
          mountPath: /models/input
        - name: default-token-tjsbd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: Always
  containers:
    - name: executor
      image: 'ghcr.io/kleveross/caffemodel_to_netdef:v0.3.0-alpha.1'
      workingDir: /models
      env:
        - name: FRAMEWORK
          value: Caffe2
        - name: FORMAT
          value: NetDef
        - name: SOURCE_FORMAT
          value: CaffeModel
        - name: SOURCE_MODEL_TAG
          value: 'klever-model-registry.kleveross-system:8080/release/caffemodel:v1'
        - name: DESTINATION_MODEL_TAG
          value: >-
            klever-model-registry.kleveross-system:8080/release/netdef:v2-caffemodel
        - name: SOURCE_MODEL_PATH
          value: /models/input
        - name: DESTINATION_MODEL_PATH
          value: /models/output
        - name: EXTRACTOR
          value: netdef
        - name: SERVER_ORMB_DOMAIN
          value: 'klever-model-registry.kleveross-system:8080'
        - name: SERVER_ORMB_USERNAME
          value: admin
        - name: SERVER_ORMB_PASSWORD
          value: ORMBtest12345
      resources: {}
      volumeMounts:
        - name: model
          mountPath: /models/input
        - name: default-token-tjsbd
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      imagePullPolicy: IfNotPresent
  restartPolicy: Never
  terminationGracePeriodSeconds: 30
  dnsPolicy: ClusterFirst
  serviceAccountName: default
  serviceAccount: default
  nodeName: master
  securityContext: {}
  schedulerName: default-scheduler
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
  priority: 0
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
status:
  phase: Failed
  conditions:
    - type: Initialized
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-03-10T06:35:14Z'
      reason: ContainersNotInitialized
      message: 'containers with incomplete status: [model-initializer]'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-03-10T06:35:14Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [executor]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2021-03-10T06:35:14Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [executor]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2021-03-10T06:35:14Z'
  hostIP: 172.27.118.204
  podIP: 10.244.0.65
  podIPs:
    - ip: 10.244.0.65
  startTime: '2021-03-10T06:35:14Z'
  initContainerStatuses:
    - name: model-initializer
      state:
        terminated:
          exitCode: 1
          reason: Error
          startedAt: '2021-03-10T06:35:18Z'
          finishedAt: '2021-03-10T06:35:33Z'
          containerID: >-
            docker://a0bfd96bf707181367a31a24a2ce3bd2483d453e021b2c06dd0ad1c27816adab
      lastState: {}
      ready: false
      restartCount: 0
      image: 'ghcr.io/kleveross/klever-ormb-storage-initializer:v0.0.8'
      imageID: >-
        docker-pullable://ghcr.io/kleveross/klever-ormb-storage-initializer@sha256:7379b72aebf5c6411015a7f9416e5e98125b7eded2ac259ebb4311d9ef5a5f20
      containerID: >-
        docker://a0bfd96bf707181367a31a24a2ce3bd2483d453e021b2c06dd0ad1c27816adab
  containerStatuses:
    - name: executor
      state:
        waiting:
          reason: PodInitializing
      lastState: {}
      ready: false
      restartCount: 0
      image: 'ghcr.io/kleveross/caffemodel_to_netdef:v0.3.0-alpha.1'
      imageID: ''
      started: false
  qosClass: BestEffort

**Comment by simon-cj** [comment]
kubectl logs -f modeljob-90360309-20210309093813-z6hkhg8h-hpvxb -c model-initializer
看下这个

**Comment by FaceGg** [comment]
@simon-cj 

Using /models as the root path
Logging to the remote registry harbor-harbor-core.harbor-system
Username: admin
Login insecurely
time="2021-03-10T06:35:18Z" level=debug msg="attempting v2 login to registry endpoint https://harbor-harbor-core.harbor-system/v2/"
time="2021-03-10T06:35:33Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get \"https://harbor-harbor-core.harbor-system/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2021-03-10T06:35:33Z" level=debug msg="attempting v2 login to registry endpoint http://harbor-harbor-core.harbor-system/v2/"
Login succeeded
Using /models as the root path
v1: Pulling from harbor-harbor-core.harbor-system/release/caffemodel
Error: harbor-harbor-core.harbor-system/release/caffemodel:v1: not found
Usage:
  ormb-storage-initializer pull-and-export [flags]

Flags:
  -h, --help         help for pull-and-export
      --insecure     allow connections to TLS registry without certs (default true)
      --plain-http   use plain http and not https (default true)
      --relayout     relayout data for model serving (default true)

harbor-harbor-core.harbor-system/release/caffemodel:v1: not found

**Comment by FaceGg** [comment]
是不是harbor配置的有问题？我是直接这么装的
kubectl create namespace harbor-system
cd ./klever-model-registry/manifests
helm install harbor ./harbor \
    --set expose.nodePort.ports.http.nodePort=30022 \
    --set expose.type=nodePort \
    --set expose.tls.enabled=false \
    --set trivy.enabled=false \
    --set notary.enabled=false \
    --set persistence.enabled=false \
    --set trivy.ignoreUnfixed=true \
    --set trivy.insecure=true \
    --set externalURL=http://172.27.118.204:30022 \
    --set harborAdminPassword="ORMBtest12345" \
    --namespace harbor-system

**Comment by simon-cj** [comment]
externalURL 的 ip 是什么地址

**Comment by simon-cj** [comment]
还有，报错是harbor 中没有这个模型，可以在 harbor 上检查下
Using /models as the root path
v1: Pulling from harbor-harbor-core.harbor-system/release/caffemodel
Error: harbor-harbor-core.harbor-system/release/caffemodel:v1: not found
Usage:
ormb-storage-initializer pull-and-export [flags]

**Comment by FaceGg** [comment]
@simon-cj 
externalURL 中的ip是服务器的地址

模型找到了
Using /models as the root path
Logging to the remote registry harbor-harbor-core.harbor-system
Username: admin
Login insecurely
time="2021-03-10T07:26:07Z" level=debug msg="attempting v2 login to registry endpoint https://harbor-harbor-core.harbor-system/v2/"
time="2021-03-10T07:26:22Z" level=info msg="Error logging in to v2 endpoint, trying next endpoint: Get \"https://harbor-harbor-core.harbor-system/v2/\": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
time="2021-03-10T07:26:22Z" level=debug msg="attempting v2 login to registry endpoint http://harbor-harbor-core.harbor-system/v2/"
Login succeeded
Using /models as the root path
v1: Pulling from harbor-harbor-core.harbor-system/release/caffemodel
ref:       harbor-harbor-core.harbor-system/release/caffemodel:v1
digest:    c841bab1130d815d454fa69b873e50833fd174465c88c5e3c796df6d59f13d48
size:      15.2 MiB
format:    CaffeModel
Status: Downloaded newer model for harbor-harbor-core.harbor-system/release/caffemodel:v1
ref:       harbor-harbor-core.harbor-system/release/caffemodel:v1
digest:    c841bab1130d815d454fa69b873e50833fd174465c88c5e3c796df6d59f13d48
size:      15.2 MiB
format:    CaffeModel

是不是因为harobr没配置https证书的问题？ormb push 的时候要加“--plain-http”才能传上去

**Comment by simon-cj** [comment]
对，没有配置 https，需要 --plain-http 才能 push 成功

**Comment by FaceGg** [comment]
@simon-cj 那请问这个怎么配置，在哪改

**Comment by simon-cj** [comment]
https 的配置方式可以看下harbor 的官方手册 https://goharbor.io/docs/2.1.0/install-config/configure-https/
