### ISSUE TITLE
[feature] Unified error code between harbor and model-registry 

### ISSUE THREAD

**Issue by simon-cj** [kleveross/klever-model-registry#25]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
the harbor error format:
```
{"errors":[{"code":"UNAUTHORIZED","message":"UnAuthorize"}]}
```
In model registry, it include Harbor api 、ModelJob  and Model Service api，so we must unify error format， so that it looks same for frontend.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
Can you explain more about the feature? I am not sure if we are on the same page according to the issue titile.

**Comment by simon-cj** [comment]
> Can you explain more about the feature? I am not sure if we are on the same page according to the issue titile.

In short， we must have same error format with harbor api， so that it looks same in frontend

**Comment by gaocegege** [comment]
SGTM

**Comment by gaocegege** [comment]
Is there any update?
