### ISSUE TITLE
[feature] Using cache instead of APIserver to get resources

### ISSUE THREAD

**Issue by gaocegege** [kleveross/klever-model-registry#29]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

https://github.com/caicloud/temp-model-registry/pull/28#discussion_r453484069

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
yeah, SGTM, I will impl it
