### ISSUE TITLE
[disscussion] How to manager harbor auth information

### ISSUE THREAD

**Issue by simon-cj** [kleveross/klever-model-registry#3]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
@gaocegege 
Only one root account, save it in k8s's secret when deploy component.
or everyone have a account, need transmit it from frontend. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by gaocegege** [comment]
As an open source project, we need a mechanism like here https://github.com/caicloud/ormb/blob/master/docs/tutorial-serving-seldon.md#create-the-seldondeployment

Use a service account and a secret in the CRD.

**Comment by gaocegege** [comment]
Then we can support both two ways you mentioned.

**Comment by gaocegege** [comment]
Can we close it? @simon-cj
