### ISSUE TITLE
[enhancement] Add API doc or API generation command

### ISSUE THREAD

**Issue by gaocegege** [kleveross/klever-model-registry#42]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

We should provide an API doc or generate API doc using the model-registry command.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
Now, we can generate API doc by executing command `make apidoc`, do you need an official API website, if not, we can close this issue now.

**Comment by gaocegege** [comment]
I tried and only found crud modeljobs and pod logs API, can we support these reverse proxy APIs?

**Comment by simon-cj** [comment]
no, we can not generate reverse proxy APIs, unless we implement harbor API(use harbor struct and redirect API) instead of reverse proxy.

**Comment by gaocegege** [comment]
LGTM
