### ISSUE TITLE
[feature] Deploy harbor with klever

### ISSUE THREAD

**Issue by simon-cj** [kleveross/klever-model-registry#61]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
@simon-cj Need set klever-model-registry and harbor nucleophilicity

**Comment by gaocegege** [comment]
> @simon-cj Need set klever-model-registry and harbor nucleophilicity

Affinity, I think. We can schedule model registry and harbor core to the same node.

**Comment by gaocegege** [comment]
We should support both Docker Compose and Helm.
