### ISSUE TITLE
[upstream] Support GPRC and HTTP at the same time

### ISSUE THREAD

**Issue by simon-cj** [kleveross/klever-model-registry#86]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind feature

**What happened**:
seldon core can not support HTTP and GRPC at the same time, please refer https://github.com/SeldonIO/seldon-core/blob/master/operator/controllers/seldondeployment_controller.go#L478-L508

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by simon-cj** [comment]
From Clive Cox:
```
At present we don't support both at the same time but want to in 1.4 at latest.
Be great to understand your use case some more. In 1.3 we will also support NVIDIA Triton Server which will allow easy serving of TensorRT models.
```
so I will follow Selon Core community.

**Comment by gaocegege** [comment]
Can we open a corresponding issue in the upstream?

**Comment by simon-cj** [comment]
> Can we open a corresponding issue in the upstream?

upstream issue: https://github.com/SeldonIO/seldon-core/issues/2378
